### ISSUE TITLE
GameDesign: Reduction of Headbobbing

### ISSUE THREAD

**Issue by C0rvus** [PSMGGamesSS2015/PSMG_SS_2015_The_Escapist#127]
Perhaps the Head could slightly bob up and down and not sideways.
Mr. Dechant mentioned the "Amnesia"-Style of bobbing.

**Comment by grimlorn** [comment]
I guess this issue is now fixed, only headbopping in sneak-mode. ;) If there any bugs or if you want the headbopping in the horizontal-axis back, reopen it.
