### ISSUE TITLE
Avatar: Head of avatar must be transparent

### ISSUE THREAD

**Issue by grimlorn** [PSMGGamesSS2015/PSMG_SS_2015_The_Escapist#136]
For the better camera script it would be nice if the head of the avatar is transparent. Dechant said in the last SprintReview, that this could be achieved by a Render Layer.

**Comment by C0rvus** [comment]
When the Render Layer fails we simply need to ask Mister Dechant how this is going to work then :)

**Comment by grimlorn** [comment]
Maybe I can help with some settings of the camera. ;)

**Comment by C0rvus** [comment]
Nobody was worried about this, and this does not seem to happen anymore?!
Therefore I will close this issue
