### ISSUE TITLE
GameDesign: Camera

### ISSUE THREAD

**Issue by Toby3011** [PSMGGamesSS2015/PSMG_SS_2015_The_Escapist#15]
We need a first person sight for our game

**Comment by grimlorn** [comment]
Darum kümmere ich mich morgen. Morgen kommt auch der GameController als Klasse sowie das Straven des Spielers.

**Comment by Toby3011** [comment]
Achso, ja ich hab das heut vormittag schon erledigt, lade es gerade hoch :D

**Comment by grimlorn** [comment]
Achsoo, ok, beim Kommentar steht, den hättest du vor fünf Minuten erst geschrieben! :D Alles klar, dann habe ich morgen weniger zu tun, vielen Dank. ;)

**Comment by Toby3011** [comment]
Habs heute in Facebook schon angekündigt, bin aber jetzt erst dazu gekommen es hochzuladen, also stimmt das mit den 5min schon :D

**Comment by grimlorn** [comment]
Ok, super! Habs erst gerade gelesen. ;) Hey, ich werde morgen den GameController versuchen fertig zu kriegen. Über den sollen dann u.a. Abfragen über die aktuelle Spielerpositionen passieren. Dann haben wir das gebündelt, zumindest wir das von Unity so empfohlen. Wahrscheinlich müsste man dann die eine oder andere Methode anpassen, aber ich denke, das sollte kein Ding sein.:D

**Comment by Toby3011** [comment]
Jo super, die schau ich mir dann mal an! Die Kamera-Implementierung ist eh sehr rudimentär, dass kann man leicht ändern :D

**Comment by C0rvus** [comment]
Camera has been implemented, therefore I'll close that ticket.
