### ISSUE TITLE
Bug: Enemies are walking in mid-air

### ISSUE THREAD

**Issue by C0rvus** [PSMGGamesSS2015/PSMG_SS_2015_The_Escapist#155]
Enemies are suddenly walking in midair whenever they hit another object. This is, perhaps, related to, that they are ascending on the other objects collider?

**Comment by julien-ur** [comment]
This Issue can be fixed by moving the enemies with their NavMesh Agent. This is also urgently needed, so they can chase the player without getting stucked everywhere. The refactored AIFollow Script already utilizes the NavMesh Agent. You can test it in the Level_2_SPRINT_REVIEW_AI_TEST Scene!

**Comment by grimlorn** [comment]
This issue is already fixed, it doesn't have to do anything with the NavMesh Agent. The knights had a conflict with the rigidbody and the character controller, so it was not possible to set any gravity on them. But for better path finding, this might be a good idea.
