### ISSUE TITLE
Bug: Player is not able to walk upstairs

### ISSUE THREAD

**Issue by C0rvus** [PSMGGamesSS2015/PSMG_SS_2015_The_Escapist#158]
We talked about it today and perhaps it is possible to add some slight velocity to make him "hover" up the stairs?

**Comment by C0rvus** [comment]
The rat is also not able to walk upstairs, it keeps walking against the stair

**Comment by grimlorn** [comment]
The player can now walk upstairs by giving her a material with nearly no friction.

**Comment by grimlorn** [comment]
For the rat, there is also a solution: Material with no friction and a capsule collider.
