### ISSUE TITLE
Movement: Walking forward only needs one step

### ISSUE THREAD

**Issue by C0rvus** [PSMGGamesSS2015/PSMG_SS_2015_The_Escapist#173]
At the moment whenever the player moves forward he walks two steps.
By walking backwards he only walks one step.

Be reducing the amount of steps by walking forward, perhaps, we could produce a better feeling of the movement behaviour.

**Comment by grimlorn** [comment]
Only one step forward now. ;) If there are any further wishes, it belongs to ticket #116 .
