### ISSUE TITLE
Bug: Footstep makes sound disappear

### ISSUE THREAD

**Issue by C0rvus** [PSMGGamesSS2015/PSMG_SS_2015_The_Escapist#198]
Seems to have something to do with "is Grounded"

**Comment by grimlorn** [comment]
I didn't add this script so i don't really know how it works... sorry. :/

**Comment by julien-ur** [comment]
The "isPlayerGrounded" Method of the PlayerMovement Script is returning false all the time, after the Player jumped the first time! However I found a quick workaround for this bug, by adding a smelly countown timer to the jump check.
