### ISSUE TITLE
Controls: Ability to pickup objects (interact with objects) via right mouse key

### ISSUE THREAD

**Issue by C0rvus** [PSMGGamesSS2015/PSMG_SS_2015_The_Escapist#36]
In our first Sprint Review the users tended to forget hitting E-Key whenever they wanted to interact with objects and clicked mouse buttons instead.
A little "survey" of the playtesters showed me, they would like to use the right mouse button for it

**Comment by julien-ur** [comment]
I for myself am used to interact with things with the left mouse button. Maybe older games used the right mouse button for it. But in all games I played the interaction took place either with "E" or the left mouse.

**Comment by julien-ur** [comment]
Maybe this is something to test when the game is in a more advanced state.
