### ISSUE TITLE
Logic: Door opening, depending on the players position

### ISSUE THREAD

**Issue by C0rvus** [PSMGGamesSS2015/PSMG_SS_2015_The_Escapist#38]
At the moment the door only opens into one direction.
In our first Sprint Review the testers were very confused when the door slammed into their faces, because they expected the door to open the other way.
I do not know how complex this is, but making it opening the correct way would be very cool.

**Comment by julien-ur** [comment]
In real world most doors only open to one side. To block the door or subtle push the player away, if he stands right in front of it, would be the better choice, I think!?

**Comment by C0rvus** [comment]
Yeah, I forgot about the real world, you are right.
So let's keep the door opening one-directional.
I have tested it right now and the player will aready be pushed subtle away.

To make the user experience a little bit better, is it possible to slow down that door-opening-animation?
Because by slowing down that animation (sinice it is a stealth game) the user won't get that feeling of slamming a door in his face.

**Comment by C0rvus** [comment]
I have moved this issue to another milestone because this is not a must-have for the second sprint review.

**Comment by C0rvus** [comment]
corresponds to #122 therefore it can be closed..Because the draggable-Script allows you to decide in which direction the door should open to.
