### ISSUE TITLE
Controls: Improvement of vertical view lock

### ISSUE THREAD

**Issue by C0rvus** [PSMGGamesSS2015/PSMG_SS_2015_The_Escapist#49]
According to #34  the player is not able to do a barrel view anymore, which is very cool!
But I would like having it improved in that view, that the locking does not act like a "stiff neck"

**Comment by C0rvus** [comment]
As you mentioned in the weekly Jour Fixe you could ask Mister Dechant about this. Because of his large experience in the gaming development he surely encountered that problems many times before.

**Comment by C0rvus** [comment]
When you look at the "Shootergame" project they same to have it solved somehow

**Comment by grimlorn** [comment]
Looked at the shootergame, found a better and intuitive solution. ;)

**Comment by C0rvus** [comment]
Thank you for your effort! I'll look at it at midnight or tomorrow morning
