### ISSUE TITLE
Generic: Creation of GameDesign-Document

### ISSUE THREAD

**Issue by C0rvus** [PSMGGamesSS2015/PSMG_SS_2015_The_Escapist#5]

**Comment by C0rvus** [comment]
I am waiting for a respones of Mister Dechant, because in our "Blockkurs" he mentioned a template he wanted to give us.

**Comment by C0rvus** [comment]
I am currently working on it and I will be uploading it tomorrow, because it will be, hopefully, finished then.

**Comment by grimlorn** [comment]
Great. If there are any questions, just post...
