### ISSUE TITLE
GameDesign: Sticky-wall-problem

### ISSUE THREAD

**Issue by grimlorn** [PSMGGamesSS2015/PSMG_SS_2015_The_Escapist#78]

**Comment by grimlorn** [comment]
Sticky-Wall-Problem still exists. Please add the material to the box collider (only for the walls) when you have time for that.

**Comment by grimlorn** [comment]
How to: Select wall --> Mesh Collider --> Material --> Add Material

**Comment by C0rvus** [comment]
This issue can be closed now, because we know what to watch for in the near future when building levels
