### ISSUE TITLE
GameDesign: Adjusting enemy movement

### ISSUE THREAD

**Issue by C0rvus** [PSMGGamesSS2015/PSMG_SS_2015_The_Escapist#81]
It would be cool when the enemy model (knight) would have a more realistic movement.
The knight already has some animations included and it would be cool if you could manage it to adapt his animation to his movement, so he is not hovering around more and is really walking instead.

I know it might be a tough challenge. Simply look how far you can get with it :)

**Comment by grimlorn** [comment]
The work to this issue is not really done yet. Adjustment, other movements etc. needed. But this is maybe up to Tobi, he writes the script, waypoints etc.

**Comment by grimlorn** [comment]
Issue doesn't make any sense as long as there is no enemy implemented. New issue will be opened when we have a enemy in the game. ;)
