### ISSUE TITLE
GameDesign: Creation of Main Menu

### ISSUE THREAD

**Issue by Toby3011** [PSMGGamesSS2015/PSMG_SS_2015_The_Escapist#99]
We need a main menu at the beginning of our game.

**Comment by C0rvus** [comment]
As discussed in our meeting, the options menu could look like this:

-Input
Slider - MouseSensitivity
Keyassignemtn
- Game
  Difficulty
- Graphics
  Slider - Brightness (Gamma)
  Resolution
  Fullscreen / windowed
  Graphics-Quality (low / medium / high)

Something like this would be cool;

**Comment by C0rvus** [comment]
Menu is done at first.
The clean up the repo for now I will close this issue.
